services:
  - type: web
    name: Kids_App
    env: java
    buildCommand: ./mvnw clean package
    startCommand: java -jar target/*.jar
    plan: free
    region: oregon
	buildCommand: |
	  sudo apt-get update && sudo apt-get install -y openjdk-17-jdk
	  ./mvnw clean package
	  envVars:
	    - key: JAVA_HOME
	      value: /opt/render/project/.java
